require:
   rubocop-rspec

Metrics/LineLength:
  Max: 120


Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Max: 17.38
  
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'vendor/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'