require:
   rubocop-rspec

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'app/router.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'vendor/**/*'
